### ISSUE TITLE
feat: add option to configure notation

### ISSUE THREAD

**Issue by zkmnnssm** [kiimesoft/runmath#1]
Your app is awesome! I love it so much!

And I have an idea, like dont' show : 1000 * 1000 = 1e+6

but show this :  1000 * 1000 = 1000000

**Comment by dubisdev** [comment]
Hi @zkmnnssm 

It shouldn't be difficult to implement it.

I'll do it when I have some time :)

**Comment by dubisdev** [comment]
This is just docs for me:

https://mathjs.org/docs/reference/functions/format.html

**Comment by dubisdev** [comment]
Hi @zkmnnssm 

Just added this, a new release is being published :)

You have now an option to choose the output format. In your case it should be `Fixed` :)

**Comment by zkmnnssm** [comment]
tks : )
