### ISSUE TITLE
add option to hide window when I press Enter in the main input box

### ISSUE THREAD

**Issue by zkmnnssm** [kiimesoft/runmath#19]
So happy to be here again! Haha!

Can I get this new feature?

BTW, Merry Christmas! 

And also we will get to the time of our  own " Christmas"  soon

**Comment by dubisdev** [comment]
Hi @zkmnnssm and thanks for your feedback!

I love the idea. I have implemented it and it will be released in next version.
You can achieve this by activating "Hide on Enter" setting.

![image](https://github.com/user-attachments/assets/f2b46517-1eea-4607-9470-802d9d52c3de)

Merry Christmas!! 🎄💫
