### ISSUE TITLE
feat: Add setting to select start hidden or not

### ISSUE THREAD

**Issue by zkmnnssm** [kiimesoft/runmath#6]
I have a little new idea now, I set RunMath to start on Windows start. but it just directly shows the window when I start my PC, and I actually don't need use it at this time，and then I have to press alt+m to hide it.

**Comment by dubisdev** [comment]
Hi @zkmnnssm thanks for your proposal

I'll work on it when I have some time ☺️

**Comment by dubisdev** [comment]
Finally added this. This won't be configurable as I think is the expected behaviour.

To fix this, make sure you have at least Runmath v1.15., then disable the autostart setting and enable it again (this should update the command that executes Runmath on Windows start).

**Comment by zkmnnssm** [comment]
cool thank you~
