### ISSUE TITLE
bug: Failed to find branch `dev`

### ISSUE THREAD

**Issue by couriourc** [kiimesoft/runmath#8]
> Action

```bash
cargo update
```

> Description

there is not git branch "dev" in "github.com/tauri-apps".is it default branch or v1?
![image](https://github.com/kiimesoft/runmath/assets/58319769/100f7935-8615-4022-a2d6-da7ae5a7768e)

> Suggestion

```diff
# Cargo.toml
- tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
- tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
+ tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace" }
+ tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace" }
```

**Comment by dubisdev** [comment]
Seems like they have recently changed the branches. I was able to execute `cargo update` three days ago (https://github.com/kiimesoft/runmath/commit/a03885a85094b8481996af41cccd08120c421f4b) and all was ok.

I'll update it later. We should use v1

**Comment by dubisdev** [comment]
Let's keep this opened until I fix It ☺️
